export const ActionTypes = {
    ADD_POST: "ADD_POST",
    EDIT_POST: "EDIT_POST",
    ADD_CATEGORY: "ADD_CATEGORY",
    SHOW_CATEGORY_DROPDOWN: "SHOW_CATEGORY_DROPDOWN",
    SHOW_POST_MODAL: "SHOW_POST_MODAL",
    SHOW_CATEGORY_MODAL : "SHOW_CATEGORY_MODAL",
    RESET_STATE: "RESET_STATE" 
}